FROM php:8.0.3-apache

# Adds the easy php extension installer from mlocati
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
  /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync

# Installs php extensions
RUN install-php-extensions bcmath bz2 calendar exif gd gettext gmp imap intl ldap xdebug
RUN install-php-extensions mysqli pcntl pdo_mysql pdo_pgsql pgsql
RUN install-php-extensions readline shmop soap sockets xsl zip

# php.ini
COPY ./php.ini /usr/local/etc/php/conf.d/php-docker.ini

# Enables Url rewriting
RUN a2enmod rewrite

# Installs Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
